### ISSUE TITLE
Wetkit Tabbed Interface Issue

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#439] opened 2012-10-01 19:05 UTC
Hi Guys,

Still loving WET, got a small issue though, was wondering if you could advise.

We're trying to use a panel's widget, specifically the tabbed interface (provided by wetkit_widgets).

There is a JS error that occurs in wetkit-tabbed-interface.js, specifically on the line starting with $(document).on.

```
Drupal.behaviors.wetkitTabbed_Interface = {
   attach: function (context, settings) {
     if ($('.ipe_tabs_interface').length) {
      var loading_finished = 'wb-loaded';
      $(document).on(loading_finished, function () {
      });
      pe.wb_load({'dep': ['resize', 'equalheights'], 'plugins': {'tabbedinterface': $(".ipe_tabs_interface", context)}},     loading_finished);
     }
   }
 }
```

My brief analysis came to the conclusion that .on() is not supported because Drupal is still running jQuery old.ancient instead of at least 1.7 which is required for on() support. However the function is empty, so is there a reason it's there even?

Removing that line though says that the next line breaks, because pe is not defined. I'm not really sure where pe is supposed to be coming from in this case - if it's a global javascript variable, we're probably missing a dependency, but otherwise it may be missing an initialization or something like that.

Simply removing those two lines makes the Javascript work, without errors but the tabs will not change. I assume the pe.wb_load action is significant therefore to this.

Steps to reproduce:
1. Install a clean version of the WET distribution.
2. {I applied the university's theme to it - if it helps, I can send it over to you so you can test in that context. If it works for you but not for me, it's probably theme related as that's the only customization I've made}
3. Create a new, one-column custom panel page.
4. Add a single widget to it, a Tabbed Interface
5. Make sure you specify at least two tabs.
6. Save and try it out.

Hope you guys can advise!

Robert

**Comment by sylus** [comment] 2012-10-02 13:34
Hmm we are using jquery_update which on the front end makes it so jquery_update is v1.7 so the $document.on should be supported. I took a look at this myself and can't reproduce.

**Comment by uottawa-wcms** [comment] 2012-10-02 13:38
kay I will enable jquery_update and try again

**Comment by sylus** [comment] 2012-10-02 13:42
Do you have jquery_update with the admin patch we are using? Kind of hacky but seems to do the trick. Also how are you adding the tabbed interface? Through the front end?

Can you paste the javascript error you get? :) Thanks for your help on this.

**Comment by uottawa-wcms** [comment] 2012-10-02 14:33
Okay, made sure jQuery_update was set to 1.7, that part works fine now. Next error message is:

Uncaught ReferenceError: pe is not defined (wetkit_tabbed_interface.js:14).

Debugging this gives me an "undefined" value for pe, so I think this is looking for a global variable pe that we don't have set (maybe because we are using our theme). Do you happen to know where it comes from?

**Comment by uottawa-wcms** [comment] 2012-10-02 14:44
Looks like the JS variable pe is defined in the wet-boew library, in pe-ap.js and that file is not being included for some reason (theme related??)

**Comment by uottawa-wcms** [comment] 2012-10-02 15:22
Alright, some more debugging later, I've figured out the following:
- Our jQuery version is still only 1.6.1 (not 1.7) despite the fact that jquery_update is installed and working. Can't seem to spot any conflicts with our theme (which doesn't include jQuery). Did you have to disable it somewhere? The 1.7 files from jquery_update are being added to my script code but are somehow being overridden (I think).
- pe looks like a wetkit thing that is going to be needed to provide mobile-friendly and accessible widgets. How can we best include this (and the other necessary libraries) in our theme? The pe-ap.js needs the wet-boew-theme variable to be set, which is handled in your specific themes (which we're not using). How can we fix that?

Mostly I just need direction, I'm sure the technical details will fall into place, but I'm not really sure what's going on with this pe-ap.js file and the theme .js files.

**Comment by mxlav** [comment] 2012-10-02 18:10
i was having issues with these exact same files back in this post https://github.com/wet-boew/wet-boew-drupal/issues/22

Eventually I rebuilt the workspace properly (at home) and with all the proper patches in place the issue went away.

**Comment by sylus** [comment] 2012-10-05 15:52
I think this was fixed with the meeting with @uottawa-wcms again please check #431 for status on Views Based Tabbed Interface (not the widget system)

**Closed as completed by sylus** 2012-10-05 15:52 UTC
