### ISSUE TITLE
French pages returning "the page you requested does not exist" error 

### ISSUE THREAD

**Issue by aminophenol** [wet-boew/wet-boew-drupal#631] opened 2012-12-12 22:25 UTC
On a fresh install of WET, I get 3 pair of demo content pages:

English - WetKit Features, WetKit Collaboration, and WetKit Demo 
French - WetKit Caractéristiques, WetKit Coopération, Wetkit Démo

All pages work using the /node/[nid] in the url's.  But when alias is used, I would get a "the page you requested does not exist" error in Drupal.  

e.g. 
http://domain/node/1  (English) -> works
http://domain/content/content-demo  (English)-> works
http://domain/node/2  (French) -> works
http://domain/content/content-demo  (French) -> Error: page not exist

Even if I click the page link in http://domain/admin/content, the French ones would not be found.

Any suggestion?  I'm on version 7.17 hoping to try out the translation function.

thanks,

dennis

**Comment by sylus** [comment] 2012-12-13 01:28
Hmm not sure what is going on. On a fresh install say for WetKit Demo. 

Title EN: Wetkit Demo
URL EN: eng/content/content-demo

Title FR: Wetkit Démo
URL FR: fra/contenu/content-demo

This works similarly for all content. How are you seeing /content/content-demo on the french page? Due to a bilinugal token the path should be either content or contenu.

**Comment by aminophenol** [comment] 2012-12-13 14:25
hmm not sure why my language prefixes are missing.  I've checked /admin/config/regional/language/edit/en and /fr and "eng" and fra" are there.  Where else should I look to enable the the language prefixes?  - Thx.

**Comment by RobJohnston** [comment] 2012-12-13 16:13
I remember a similar problem with our all Microsoft setup (IIS, SQL Server).  If I recall correctly, we had to go the the /admin/config/regional/language page and re-save English as the default or toggle the default to French then back to English.

**Comment by sylus** [comment] 2012-12-13 16:16
Hey @aminophenol what is your stack?

**Comment by aminophenol** [comment] 2012-12-13 16:25
That did the trick! And indeed I'm on IIS/SQL.  I didn't mention this as I wouldn't think it mattered.  Proves me wrong again.  

Thanks!

**Comment by sylus** [comment] 2012-12-13 16:47
Hmm ideally you shouldn't have to do this. Any ideas on a fix for this @RobJohnston . I guess in the mean time can make a note saying this has to be done?

**Comment by RobJohnston** [comment] 2012-12-13 16:53
No idea of a fix @sylus, another person here stumbled across this work-around and nobody's gone back to investigate what changes in the DB when English is re-saved (presuming that's it, of course).

**Comment by sylus** [comment] 2013-02-06 03:46
Closing this issue as might have been fixed with all of the updates. If problem happens again please re-open.

**Closed as completed by sylus** 2013-02-06 03:46 UTC
Labels: Bug Report: Minor

**Comment by RobJohnston** [comment] 2013-11-28 18:27
Revisiting this old issue because the problem has never gone away but I found that after a fresh install, "drush vget language_count" returned "-1".  I then ran "drush vset language_count 2" and the problem was fixed.

**Comment by sylus** [comment] 2013-11-28 18:30
Checked latest dev and it is set as 

```

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'language_count';
  $strongarm->value = 2;
  $export['language_count'] = $strongarm;
```

What version is this with?

**Comment by RobJohnston** [comment] 2013-11-28 18:31
RC25... I checked and saw the same in wetkit_language.strongarm.inc.  It's a puzzler.

**Comment by sylus** [comment] 2013-11-28 18:32
This is for MSSQL? I can't reproduce in MySQL or Postgresql as get the expected value when using vget.

**Comment by RobJohnston** [comment] 2013-11-28 18:32
Yes, it is only with MS SQL Server.  I can't reproduce it either with the other DBs.
