### ISSUE TITLE
Incorrect syntax near the keyword 'CONVERT'

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#421] opened 2012-09-19 14:22 UTC
I'm going to guess this is just an MS SQL Server dialect difference.  The last install I did on  August 31st worked fine.  Following is the error:

<code><pre>
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. 
&lt;snip&gt;
Home Installation tasks
Choose profile(done)
Choose language(done)
Verify requirements(done)
Set up database(done)
Install profile(active)
Configure site
Choose a theme
Import French Language
Finished Status message 
Custom Search enabled. Don't forget to set permissions. 
Refreshed 2 strings for the enabled modules. 
Refreshed 8 strings for the enabled modules. 
Refreshed 10 strings for the enabled modules. 
To use menu blocks, find the "Add menu block" link on the administer blocks page. 
Password policy module successfully installed. Please review the available configuration settings. 
Warning message The image resize filter has been installed. Before this does anything, the image resize filter needs to be added to one or more text formats. Visit the text format administration to set up this filter. 
SQLSTATE[42000]: [Microsoft][SQL Server Native Client 10.0][SQL Server]Incorrect syntax near the keyword 'CONVERT'. 
</pre></code>

I've done a search around the Drupal site and don't see a reference to this error anywhere else.  Any clues or pointers?

**Comment by sylus** [comment] 2012-09-19 14:50
Hey @RobJohnston this is due to a patch we are using for search_api_db we need to fix this soon as it is breaking postgres installs. Closing this issue as it is a duplicate of #379.

Please take a look at the issue and if you have a suggestion as to how postgres would deal with utf8 bin collection we can submit our own pach to fix this problem :)

**Closed as completed by sylus** 2012-09-19 14:50 UTC
