### ISSUE TITLE
Translation of Menus

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#113] opened 2012-07-18 19:00 UTC
Hi Guys,

Still reviewing and working into your code and configuration.  Trying to get a handle on some of the decisions made for the out of the box configuration.

I am looking at the Menus and I see that you translate the menus within the English parent menu object rather than using the "Translation Set" feature (creating a English menu and a French menu as separate objects and relating them after wards)

Any specific reason for doing this?

Thanks

**Comment by sylus** [comment] 2012-07-18 19:10
Hey @StephenOTT there was a reason for this as i18n had problems with the translation set feature particularly when relating back to the node. That being said this was a few months ago and i18n has had some significant changes since then. It might be time to check out how functional this is as of now :)

**Comment by joejoseph00** [comment] 2012-07-25 14:58
Note on Translations, I tried to install Wet Kit Distro in french and it froze the install, I plan on re-testing and checking for log messages later.

Note: I have installed other distros of Drupal 7 in french and they installed correctly.  

Also note:  Federal operations in Ottawa/Gatineau are officially designated bilingual work zones where French and English have equal status in terms of the work environment, that means ideally computer software used by workers is normally expected to function in both languages as preferred by the worker.  English is fine in federal zones such as most of western Canada where the official working language is english only (french services are provided in a  limited manner in those unilingual zones)
There are also federal govt unilingual french zones where english services are limited and the work language is french, such as most of Québec (excluding parts of Montréal and most or all of Gatineau's federal installations which are bilingual zones and where english and french are equal status at the federal level) and parts of New Brunswick, actually N.B is also an officially bilingual province but I'm not familiar with their policies.

So just saying that there are use cases for installing in french.

Also, if we want collab from other governments in other countries like Belgium for example, neither of their official languages are english, so they would very likely prefer to either install in Dutch or French and they likely have similar requirements to us.  

It might be a good idea to think about this so that we can make this project international and perhaps give a bigger profile to this project even though it's really designed for the Federal govt, a lot of other organizations like the City of Ottawa are showing interest and will likely take the wet kit theme and modify it.

**Comment by sylus** [comment] 2012-07-25 15:03
Hey @joejoseph00 thanks for taking a look at this. The french install did work at some point but likely some regression got added in. Since it works in english it is probably a trivial bug that just needs to be tracked down. I am in complete agreement with you over French being a priority and am committed to making the experience perfect in either official language. :)

**Comment by sylus** [comment] 2012-08-01 16:03
All fixed up! :)

**Closed as completed by sylus** 2012-08-01 16:03 UTC
Labels: Support Request
