### ISSUE TITLE
MS SQL Server installation error on or after "Import content" step.

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#745] opened 2013-02-14 16:33 UTC
Got an error installing the latest and greatest on a MS SQL Server database.  My guess is a SQL dialect issue just after importing content.

```
An AJAX HTTP error occurred. 
HTTP Result Code: 200 Debugging information follows. 
Path: http://pm.local/install.php?profile=wetkit&locale=en&welcome=done&id=3&op=do 
StatusText: OK 
ResponseText: Home | Web Experience Toolkit Home Installation tasks
Welcome(done)
Verify requirements(done)
Set up database(done)
Install profile(done)
Configure site(done)
Choose a theme(done)
Import French Language(done)
Import content(active)
Finished Processed 6 (6 created, 0 updated, 0 failed, 0 ignored) in 1.7 sec (217/min) - done with 'WetKitMigrateDefaultContent' 
SQLSTATE[42000]: [Microsoft][SQL Server Native Client 10.0][SQL Server]Incorrect syntax near '='.
```

**Comment by sylus** [comment] 2013-02-14 19:19
Hmm this looks like PostImport issue which I think only uses mysql syntax.

Syntax look wrong for mssql?

https://github.com/wet-boew/wet-boew-drupal/blob/master/modules/custom/wetkit_migrate/migrations/default_content/migrate_default_content.inc#L29-138

As a quick bug fix can make migrate optional whether using drush or browser install.

**Comment by RobJohnston** [comment] 2013-02-14 19:23
I was trying to track things down and I got to that... I've been doing a lot of migration lately and it looks good to me.  I can even say that in the database there are 6 nodes created and the translation IDs are set correctly (meaning postImport ran), so I think the problem is happening on a subsequent step.

I'm doing a browser-based install on Linux/Apache/MySql right now to see if it's really a problem with MS SQL or the browser-based install.

**Comment by sylus** [comment] 2013-02-14 19:26
Then I am thinking it is bean module:

https://github.com/wet-boew/wet-boew-drupal/blob/master/wetkit.install_callbacks.inc#L24-41

Can you see if beans were imported? This was a new addition and just released as v1.0 so could be likely.

After this we should work on having Travis test mssql databases to minimize this regressions in the future.

**Comment by RobJohnston** [comment] 2013-02-14 19:32
I'm thinking beans too.  After the error showed I click on the "Please continue to the error page" link and got the "WetKit installation complete" screen with a link to the new site.  The home page of the new site has the content in the left-side and nothing else.  In the centre is "Bean with delta Videos does not exist, please create it first" and the right-side has the same message about Priorities and Minister.

Looks like it conked-out after the content creation and before beans, so right where you said.  Must be coming from the "bean_create" function??

**Comment by sylus** [comment] 2013-02-14 19:34
Yeah completely agree. We should file an issue with the bean module and mark it as critical.

Do you have a Drupal site already installed where you can try to add Bean module manually to verify?

I'd try it first vanilla, then with entity translation.

**Comment by RobJohnston** [comment] 2013-02-14 19:38
My browser-based install on Linux/Apache/MySql is currently importing bean content, so it's worked past the problem.  Looks like an MS SQL Server issue.  I'll run it once more on another server just to be sure.

**Comment by RobJohnston** [comment] 2013-02-14 21:16
So I put in some watchdog messages and can say that it runs past the call to entity_get_controller() in the entity_create() function of /profiles/wetkit/modules/contrib/entity/entity.module.

Then I created a bean and got this error:

```
PDOException: SQLSTATE[42000]: [Microsoft][SQL Server Native Client 10.0][SQL Server]
Incorrect syntax near '='.: 
  SELECT revision.[vid] AS [vid], 
    revision.[uid] AS [uid], 
    revision.[delta] AS [delta], 
    revision.[label] AS [label], 
    revision.[title] AS [title], 
    revision.[type] AS [type], 
    revision.[view_mode] AS [view_mode], 
    revision.[data] AS [data], revision.[log] AS [log], 
    revision.[created] AS [created], 
    revision.[changed] AS [changed], 
    base.[bid] AS [bid], 
    base.vid = revision.vid AS default_revision 
  FROM {bean} base 
    INNER JOIN {bean_revision} revision ON revision.vid = base.vid 
  WHERE ( ([base].[delta] IN (:db_condition_placeholder_0)) ); 
Array ( [:db_condition_placeholder_0] => Priorities-TEST1 ) 
in EntityAPIController->query() 
(line 187 of C:\inetpub\wwwroot\drupal_wet\profiles\wetkit\modules\contrib\entity\includes\entity.controller.inc).
```

The offending SQL is the equals sign in the selected parameter right before the FROM clause.

**Comment by sylus** [comment] 2013-02-14 21:19
This is an awesome report. Can you file this as an issue marked critical for bean. I'll chime in and second the post.

**Comment by RobJohnston** [comment] 2013-02-14 21:22
OK.  I'll do it when I get home, or sometime this evening.  Good night

**Comment by sylus** [comment] 2013-02-14 21:23
Awesome thanks for your help. I'd assume once the issue is filed it will get fixed rather quickly. More then a few distros (Agov, Commerce) are now using bean. So this issue will definitely be high priority especially for government who can often use MSSQL.

Thanks again!

**Comment by RobJohnston** [comment] 2013-02-14 23:21
@sylus, Done.  See http://drupal.org/node/1917732.  Going back for nap now.

**Comment by RobJohnston** [comment] 2013-04-15 14:05
I think I just found the final solution here:
http://drupal.org/node/1809346
I can now create a bean post-install.  May wait for RC2 to come out to see that it works during install.

**Comment by sylus** [comment] 2013-09-09 17:53
I am going to close this issue as there is a workaround documented. I don't think we can add this by default though. However issue will be present for others having the same problem :)

**Closed as completed by sylus** 2013-09-09 17:53 UTC
Labels: Upstream, Bug Report: Major
