### ISSUE TITLE
CSS Messages broken in Safari

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#282] opened 2012-08-27 01:22 UTC
Messages boxes when viewed in safari are "scrambled"/broken.

**Comment by StephenOTT** [comment] 2012-08-27 01:27
See link for image of issue:
https://www.dropbox.com/s/1abdvb1inervf1k/Untitled.tiff

**Comment by sylus** [comment] 2012-08-27 01:55
Hmm I can't see this error in my safari:

http://dl.dropbox.com/u/38413195/fixes_08_26_2012/no_error.png

**Comment by sylus** [comment] 2012-08-27 01:56
This may be an error with WET itself. What version of Safari are you running?

**Comment by StephenOTT** [comment] 2012-08-27 01:57
mmmm....  I have cleared my caches several times....  I will look into it further on my end.

**Comment by StephenOTT** [comment] 2012-08-27 01:58
Running latest. 6.0 Mac.
I did notice the same issue on the ircan WET examples pages.

**Comment by StephenOTT** [comment] 2012-08-27 02:08
I cannot get the issue to go away on my side.....
Not sure what is causing it.  Chrome and Firefox work perfect.  But on safari even aften cache clears and full resets on the browser, issue is still there....

**Comment by sylus** [comment] 2012-08-28 18:10
Do you notice the issue here? http://wet-boew.github.com/wet-boew/demos/grids/grid-message-eng.html

**Comment by sylus** [comment] 2012-08-28 23:55
Closing this for now as can't reproduce but please reopen if problem persists and is not experienced with the link above. It the link above also has same problem. An issue should be filed with WET-BOEW linking this issue. ^_^

**Closed as completed by sylus** 2012-08-28 23:55 UTC

**Comment by StephenOTT** [comment] 2012-08-28 23:56
Thanks @sylus.
Doing great work!

On 2012-08-28, at 7:55 PM, William H notifications@github.com wrote:

Closing this for now as can't reproduce but please reopen if problem
persists and is not experienced with the link above. It the link above also
has same problem. An issue should be filed with WET-BOEW linking this
issue. ^_^

—
Reply to this email directly or view it on
GitHubhttps://github.com/wet-boew/wet-boew-drupal/issues/282#issuecomment-8111256.
