### ISSUE TITLE
Configuring WYSIWYG

### ISSUE THREAD

**Issue by liquidcms** [wet-boew/wet-boew-drupal#658] opened 2012-12-20 20:59 UTC
I go to edit a Basic Page and i see i have the format options of wysiwyg, plain text and html: http://screencast.com/t/rSkd6njAQ4nd

and when picking wysiwyg i get a TinyMCE toolbar at the top of the edit window. good so far.

the way this should work is that Better Formats links the input format "wysiwyg" to a configuration of Tiny. But when i go to the better formats page and from there edit the Tiny config; none of these config changes show up when i edit a page.

any idea what is breaking this?

**Comment by sylus** [comment] 2012-12-21 03:22
Think this is related to us manually declaring the default values without taking into account the user changes on the better formats screen. If this is the cause should be simple enough to fix.

https://github.com/wet-boew/wet-boew-drupal/blob/master/modules/custom/wetkit_wysiwyg/wetkit_wysiwyg.module#L210-211

**Comment by sohananktech** [comment] 2012-12-24 07:13
You should use http://drupal.org/project/wysiwyg module and 
Tinymce as libraries http://www.tinymce.com/download/download.php

**Comment by liquidcms** [comment] 2012-12-24 07:49
Yes, these are the defaults used in the distro and are what i am configuring. I think Will's suggestion is likely the issue here: the settings are hard coded and should not be.

**Comment by sylus** [comment] 2013-09-09 17:51
Fixed with CKEditor instead of TinyMCE.

**Closed as completed by sylus** 2013-09-09 17:51 UTC
Labels: Bug Report: Minor
