### ISSUE TITLE
Error notice on module admin UI when coming from Apps UI

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#274] opened 2012-08-25 20:40 UTC
following error appears:
Notice: Undefined offset: 0 in apps_preprocess_apps_app_featured() (line 117 of /Users/myuser/Sites/OttawaWET/drupal_wet2/profiles/wetkit/modules/contrib/apps/theme/apps.theme.inc).
Notice: Undefined variable: screenshot in include() (line 11 of /Users/myuser/Sites/OttawaWET/drupal_wet2/profiles/wetkit/modules/contrib/apps/theme/apps-app-featured.tpl.php).

Error appears on the Modules (Admin>Modules) window, under the following condition:
1. Go Admin>Apps>WetKit (Local Apps)
2. Then select Modules from the Admin bar.

The error will appear.

**Comment by sylus** [comment] 2012-08-30 03:10
Marking as a duplicate of #194 since stems from the same problem. I have talked to febbraro and he expects a fix later in the week.

**Closed as completed by sylus** 2012-08-30 03:10 UTC
Labels: Bug Report: Minor
