### ISSUE TITLE
Intranet: Server Warning Pages Broken

### ISSUE THREAD

**Issue by csedev** [wet-boew/wet-boew-drupal#289] opened 2012-08-27 19:11 UTC
The Intranet server message pages aren't loading properly.   See attached screenshot.  

![Access Denied Screenshot](http://www.opin.ca/dvp/access-denied.png)

**Comment by sylus** [comment] 2012-08-27 19:30
I can't reproduce this. Can you grab the absolute latest and check your permissions?

**Comment by sylus** [comment] 2012-08-27 19:32
Check out http://wet.openplus.ca I switched to Intranet mode and everything is a-ok.

**Comment by sylus** [comment] 2012-08-27 19:34
Oh actually I can, it is something to do with adaptivetheme + generated_files and permissions. A secondary save seemed to fix it but think it has to do with the generated_files not having permissions on the server to regenerate themselves. I likely should be saving them in default/files rather then in the theme.

**Comment by StephenOTT** [comment] 2012-08-27 21:13
I ran into the same problem the other night after your recent pull request and i ran a drush update on the config.  Did not troubleshoot just reinstalled base

**Comment by sylus** [comment] 2012-09-06 12:03
Looks fixed now!

**Closed as completed by sylus** 2012-09-06 12:03 UTC
Labels: Bug Report: Minor
