### ISSUE TITLE
Support for overlay?

### ISSUE THREAD

**Issue by uottawa-wcms** [wet-boew/wet-boew-drupal#499] opened 2012-10-26 16:23 UTC
@sylus I know we talked last month about using the overlay to solve certain problems, thought you should know that I just found a conflict between it and WET.

If you install wet clean and then simply run drush en -y overlay, then try to do either of the following:
1. Create enough content, then try and change between pages of content at the bottom
2. Apply a filter at the top

Then you get a javascript alert box with code 200 OK but saying that a parseerror occured.

**Comment by sylus** [comment] 2012-10-30 20:41
Overlay is crepping back in based on:

Drupal newbies sometimes have difficulty navigating a Drupal site. Overlay attempts to address this by maintaining non-admin context separately, so the user can easily return to the content they were viewing before they entered the admin interface.

Newbies also sometimes don't understand which parts of their site will be publicly visible. Overlay shows admin pages in a visually distinct interface, to make it clear which pages are only visible to admins.

Experienced site builders and developers can easily disable the overlay, but newbies wouldn't even know it exists or how to enable it unless it is already enabled by default.

However I am not able to replicate a javascript alert? What do u mean by step 1?

**Comment by ottawadeveloper** [comment] 2012-10-31 13:15
When you create more than 50 pages of content, and then try to use the pager at the bottom of admin/content, it fails with an AJAX message. 

You can also duplicate it by trying to use one of the filters (not Operations, but the Type filter for example) at the top of the admin/content page. 

It only bugs out if you have overlay enabled and the admin/content page is being displayed using the overlay.

**Comment by sylus** [comment] 2012-11-01 01:22
Hmm I can't reproduce this on latest master we have. Perhaps it got resolved in an earlier commit?

**Comment by ottawadeveloper** [comment] 2012-11-01 13:04
Trying a fresh install from master now.

**Comment by ottawadeveloper** [comment] 2012-11-01 13:42
Nope, I just reproduced it perfectly. I can do an archive-dump if you want to check out the site, but I just did this:
1. Drush make to build the installation locally
2. Site installed 
3. Made sure the overlay was enabled (it was).
4. Made sure update.php didn't have anything to run
5. Created a piece of content (a Basic Page with the minimum of settings)
6. Went to admin > content
7. Changed the page type filter to "Basic Page"
8. Applied the filter
9. Got a JS error (see below)

This was done on our CentOS server with a MySQL database. 

I did get one weird error during the site install, it complained about a column not being defined for search_db_api (an index_nid column) but it appeared to recover fine. After I did the steps above, I went back and disabled search_api and search_api_db to make sure they weren't the problem. 

Here's the JS popup I get. I'm thinking that the issue is the @import statements causing the JSON to not be parsed appropriately.

```
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /base3/?q=views/ajax&render=overlay
StatusText: OK
ResponseText: 
  @import url("http://chomp.cc.uottawa.ca/base3/modules/system/system.base.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/modules/system/system.menus.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/modules/system/system.messages.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/modules/system/system.theme.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/modules/overlay/overlay-child.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/sites/all/modules/contrib/jquery_update/replace/ui/themes/base/minified/jquery.ui.core.min.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/sites/all/modules/panopoly/panopoly_core/css/panopoly-jquery-ui-theme.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/sites/all/modules/contrib/jquery_update/replace/ui/themes/base/minified/jquery.ui.accordion.min.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/sites/all/modules/contrib/date/date_api/date.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/sites/all/modules/contrib/date/date_popup/themes/datepicker.1.7.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/sites/all/modules/contrib/fences/field.css?mct9mc");
  @import url("http://chomp.cc.uottawa.ca/base3/modules/node/node.css?mct9mc");
  @import url(
    "http://chomp.cc.uottawa.ca/base3/sites/all/mo...gets.js":1,
    "profiles\/wetkit\/modules\/custom\/wetkit_widgets\/wetkit-tabbed-interface.js":1,
    "sites\/all\/modules\/contrib\/caption_filter\/js\/caption-filter.js":1,
    "sites\/all\/modules\/contrib\/panels\/js\/panels.js":1,
    "sites\/all\/modules\/contrib\/devel\/devel_krumo_path.js":1,
    "sites\/all\/modules\/contrib\/custom_search\/js\/custom_search.js":1,
    "misc\/autocomplete.js":1,
    "misc\/tableheader.js":1,
    "sites\/all\/modules\/contrib\/views\/js\/base.js":1,
    "misc\/progress.js":1,
    "sites\/all\/modules\/contrib\/views\/js\/ajax_view.js":1,
    "misc\/collapse.js":1,
    "sites\/all\/modules\/contrib\/views_bulk_operations\/js\/views_bulk_operations.js":1
  }},
  "overlayChild":{
    "closeOverlay":true,
    "redirect":"\/base3\/?q=views\/ajax",
    "refreshRegions":[{"region-page-bottom":"page_bottom"}],
    "refreshPage":true},
    "CToolsModal":{
      "modalSize":{
        "type":"scale",
        "width":".9",
        "height":".9",
        "addWidth":0,
        "addHeight":0,
        "contentRight":25,
        "contentBottom":75
      },
      "modalOptions":{
        "opacity":".55",
        "background-color":"#FFF"
      },
      "animationSpeed":"fast",
      "modalTheme":"CToolsModalDialog",
      "throbberTheme":"CToolsModalThrobber"
    },
    "spotlight_settings":{
      "rotation_time":4000
    },
    "custom_search":{
      "form_target":"_self",
      "solr":0
    },
    "views":{
      "ajax_path":"\/base3\/?q=views\/ajax",
      "ajaxViews":{
        "views_dom_id:e3c484171c25c001bccfeb46f91df52c":{
          "view_name":"admin_views_node",
          "view_display_id":"system_1",
          "view_args":"",
          "view_path":"admin\/content",
          "view_base_path":"admin\/content",
          "view_dom_id":"e3c484171c25c001bccfeb46f91df52c",
          "pager_element":0
        }
      }
    }
  }
);
```

**Comment by sylus** [comment] 2012-12-05 20:37
Overlay is now permanently gone, causes too much hassle and the improved rubik addresses many visual issues I was initially worried about.

**Closed as completed by sylus** 2012-12-05 20:37 UTC
Labels: Support Request
