### ISSUE TITLE
Error Notice on Dashboard Media Page

### ISSUE THREAD

**Issue by StephenOTT** [wet-boew/wet-boew-drupal#265] opened 2012-08-25 17:41 UTC
Notice: Trying to get property of non-object in file_icon_path() (line 809 of /Users/myuser/Sites/OttawaWET/drupal_wet2/modules/file/file.module).
Notice: Trying to get property of non-object in file_icon_map() (line 852 of /Users/myuser/Sites/OttawaWET/drupal_wet2/modules/file/file.module).
Notice: Trying to get property of non-object in file_icon_path() (line 824 of /Users/myuser/Sites/OttawaWET/drupal_wet2/modules/file/file.module).
Notice: Trying to get property of non-object in file_icon_path() (line 824 of /Users/myuser/Sites/OttawaWET/drupal_wet2/modules/file/file.module).
Notice: Trying to get property of non-object in file_icon_path() (line 824 of /Users/myuser/Sites/OttawaWET/drupal_wet2/modules/file/file.module).
Notice: Trying to get property of non-object in file_icon_path() (line 824 of /Users/myuser/Sites/OttawaWET/drupal_wet2/modules/file/file.module).

Showing up at: Dashboard>Media

**Comment by sylus** [comment] 2012-08-25 17:52
Issue is reported here: http://drupal.org/node/1621474

**Comment by sylus** [comment] 2012-08-30 03:23
Duplicate of #194 all part of the same problem fix coming soon, will update #194 once ready.

**Closed as completed by sylus** 2012-08-30 03:23 UTC
Labels: Bug Report: Minor
