### ISSUE TITLE
Add box, Add multilingual box, and editing an existing box not working

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/wet-boew-drupal#537] opened 2012-11-15 18:33 UTC
Just did a fresh install this morning at 11:11 (Linux & postgres).

So on the /admin/structure/block page, I'm presented with 4 options at the top:  Add block, Add box, Add menu block, and Add multilingual box.  The two block ones work but the two box ones do not (nothing is created and no error message is shown in the "Recent log messages" report.

I noticed this because I couldn't edit the "Priorities Box" or "Minister Box" that are on the front page via the "Blocks" page.  On my older Windows & sqlsrv installation I can only change the priorities box by editing the file at /profiles/wetkit/modules/custom/wetkit_wetboew/wetkitwetboew.box.inc.

I though that this morning's issue #534 by @jomuji would get to this but it hasn't.

I've noticed the problem with those two front page boxes for awhile and am surprised that nobody else has mentioned it, so is it just me?

**Comment by sylus** [comment] 2012-11-16 14:55
Oh this regression must have creeped in will take a look ^_^ Thanks for the heads up!

**Comment by sylus** [comment] 2012-11-20 14:39
Can confirm updating to Drupal 7.17 causes this. Still tracking down!

**Comment by RobJohnston** [comment] 2013-01-23 19:09
Upgraded to Drupal 7.19 and this issue may be solved now.  I can create a new multilingual box and edit the existing Minister's box.  Can someone else confirm so this issue can be closed?  Drupal 7.18 still seems to not work.

**Comment by sylus** [comment] 2013-01-30 15:04
Yeah can confirm this works again in 7.19. Not sure what the problem was in 7.18. Closing this issue for now but again really hoping to soon replaces boxes with beans.

**Closed as completed by sylus** 2013-01-30 15:04 UTC
Labels: Bug Report: Major
