### ISSUE TITLE
Drupal 7.19 WetKit mega menu and IE8 issues

### ISSUE THREAD

**Issue by Phr34ks0w** [wet-boew/wet-boew-drupal#758] opened 2013-02-22 16:01 UTC
Hi @sylus,

I don't know if you can help me. I think I remember seeing something about Drupal and/or WetKit not working properly in IE8. We're presently having an issue with the mega menu and IE8. It is not displaying properly (styling issues). I tried the "Explorer 8 Mode" module but it made it worst. But everything works/displays fine in Firefox update 19. If nothing can be done on this. Where can I find a written statement that IE8 doesn't work with Drupal/WetKit so I can bring the info to my director. Please see attachments.

Much appreciated.
Pat
![firefox19_drupal](https://f.cloud.github.com/assets/2170704/185499/fdc488a0-7d08-11e2-9747-69260da9a1b9.JPG)
![IE8_drupal](https://f.cloud.github.com/assets/2170704/185501/088fec2a-7d09-11e2-89b1-05b9df35ff9b.JPG)

**Comment by sylus** [comment] 2013-02-23 17:26
We are running the WetKit Drupal in IE8 for Stats as that is our current browser. The problem is one edge case in the mega menu. Where you are not using a nesting of depth 2 for all of the menu items.

I am going to try to fix this this weekend. I don't think it will be a hard fix.

Other then the mega menu are there other problems you are experiencing? I will for sure resolve this quickly. Possibly by Sunday.

**Comment by sylus** [comment] 2013-02-23 17:31
See: http://wet-boew.github.com/wet-boew/demos/index-eng.html

Section 2 is the problem

When I do the fix are you able to test for me?

**Comment by Phr34ks0w** [comment] 2013-02-25 18:22
The link you sent me (previous message) works fine in my IE8. The section 2 is OK. Another issue I'm having is in  the admin environment. When I click on the button "Customize this page", I get an IE File download dialog box prompting me to save a file name "panel_context_page-wetkit_demo_panel_front__page_wetkit_demo_panel_front_panel_context____". Same result with the button Change this layout". But, again everything works fine in Firefox update 19. No issues whatsoever.

Thanks

**Comment by sylus** [comment] 2013-02-26 01:19
Just pushed a fix for the menu system in master branch. Will be included in HotFix 2 release.

**Comment by Phr34ks0w** [comment] 2013-02-26 16:40
Hi @sylus, 

I updated my installation with:
cd profiles/wetkit && git pull && cd .. && cd .. && drush make --working-copy profiles/wetkit/build-wetkit.make --yes

and 

drush -l http://<domain>:8082 updatedb (with my server's IP)

And now everything looks good in IE except that the nested child list items don't show at all in IE8 and Firefox update 19 now. The only thing that shows is the parent items (main mega menu and no child. The update process went well with no errors.

Thanks

**Comment by Phr34ks0w** [comment] 2013-02-26 16:45
![drupal_menu](https://f.cloud.github.com/assets/2170704/197191/bd97d3c6-8033-11e2-893e-69e87a79f782.JPG)

Under "A propos du SATJ", there should be 2 sub items (same for english) but they don't show anymore.

**Comment by sylus** [comment] 2013-02-27 17:01
Can you attach a screen shot of the menu links themselves in the UI. So I can see how they are structured and with depth.

I have to think something went down with the update.

**Comment by Phr34ks0w** [comment] 2013-02-27 17:51
Hi,
Here is the menu config:
![mega_menu](https://f.cloud.github.com/assets/2170704/202027/e658b2ae-8104-11e2-82ff-cf20c566513b.gif)

Here are the results in IE8 & IE9 & FF19
![menu_items](https://f.cloud.github.com/assets/2170704/202037/2be27f94-8105-11e2-8b2e-9a2eabaabee6.gif)

Here is each sub items results:
![menu_items_b](https://f.cloud.github.com/assets/2170704/202071/2c43c4e2-8106-11e2-9597-2f2f20c8f38b.JPG)
![menu_items_a](https://f.cloud.github.com/assets/2170704/202079/5ad444da-8106-11e2-91f2-171894cc1124.JPG)

**Comment by Phr34ks0w** [comment] 2013-02-27 18:07
but if I click on the actual page, I get a proper side menu...

![side_menu](https://f.cloud.github.com/assets/2170704/202141/7e289c18-8108-11e2-812d-477b3c67b588.JPG)

**Comment by mxlav** [comment] 2013-03-02 13:32
I brought in the patch and also am missing the child menues.

**Comment by Phr34ks0w** [comment] 2013-03-06 19:35
Hi guys, any updates on this issue? Thanks

**Comment by sylus** [comment] 2013-03-07 21:19
Thinking is same as #776 so closing this issue and progress will be posted over there.

**Closed as completed by sylus** 2013-03-07 21:19 UTC
