### ISSUE TITLE
Building Drupal WET through Aquia Developer desktop problems

### ISSUE THREAD

**Issue by MaddyDaigle** [wet-boew/wet-boew-drupal#736] opened 2013-02-11 19:32 UTC
Hello,

I've been trying to follow the documentation provided here (https://github.com/wet-boew/wet-boew-drupal/wiki/Download%2C-Installation%2C-and-Update) in order to install Drupal WET on the Aquia Developer Desktop.  Unfortunately this documentation seems to be out of date with the commands provided in the main project page.  I need to do the Drush installation of WET Drupal on my local machine since I have to connect to our servers through VPN and cannot use Drush commands on the server.

Any help would be appreciated.

Thanks.

**Comment by sylus** [comment] 2013-02-13 14:52
Hey @MaddyDaigle can you follow the instructions on the main page and highlight which command is causing problems for you? I will update the other documentation shortly.

**Comment by DanMorand** [comment] 2013-02-13 17:19
I'm using the same instructions and had some problems too, where the new database doesn't get created in Acquia Dev. It's been a little tricky to follow those steps (for us in any case.) I think I saw a difference in Git/Drush versions on different instruction pages.

We're trying to get some Windows XP installations done today at work (no proxy) so we can have a Dev environment. I'm hoping to get the same package installed at home on Windows 7.

I should clarify that we are using Drush, the problem is just getting the package installed properly with that instruction set.

**Comment by Tikka** [comment] 2013-02-14 13:00
By chance @MaddyDaigle, did your difficulty start with this command:

drush make --prepare-install --no-gitinfofile --working-copy profiles/wetkit/build-wetkit.make --yes

**Comment by sylus** [comment] 2013-02-14 19:30
Hey @DanMorand and @MaddyDaigle are you guys able to talk tomorrow I'd like to fix up the docs to minimize these types of problems in the future. Was thinking if we talked could find where the instructions are falling short.

We are soon getting Drupal.org approval so the drush make step will be done automatically but still waiting for final approval. http://drupal.org/node/1494484

**Comment by Tikka** [comment] 2013-02-14 20:39
Please include me. I can open up any time tomorrow. We are implementing this as we speak, and are highly motivated to contribute in any way. The unfortunate part is that we are new. Me, more so than the rest. I want to contribute, especially with documentation, I'd love to be helpful despite my newbie drupal status.

**Comment by MaddyDaigle** [comment] 2013-02-14 23:23
Sure! I've been ill the past couple days but I should be back tomorrow. The issue was actually with the drush commands and running them on windows. Sorry I didn't clarify.  I managed to get everything working from my Mac at home using MAMP, but I'm still having issues on windows. I tried all the suggestions provided on the Issues (running the windows Git in bash mode, using the correct file path convention, etc..) but I still couldn't get it working.

**Comment by sylus** [comment] 2013-02-15 00:57
Ah okay I can definitely help with this. Windows is definitely tricky! :)

**Comment by MaddyDaigle** [comment] 2013-02-15 13:36
Let me know when you want to talk.  I can help out with documenting the process as well. :)

**Comment by DanMorand** [comment] 2013-02-15 15:15
I'm available whenever you have some time. It's a Windows issue for us too, specifically with the Acquia Dev Desktop installation. We're on XP here at work but I'm hoping to get the same dev environment set up at home on Windows 7.

Good news about progress with the code review, and kudos for all the time (and expertise) you've put into it @sylus. Drupal + WET is going to be a game-changer.

**Comment by sylus** [comment] 2013-02-15 15:58
How about today at 2:00? Unfortunately I can't get a teleconference line today I don't suppose anyone here is able to set that up? :P

**Comment by MaddyDaigle** [comment] 2013-02-15 16:06
We should be able to set it up here at the RCMP.  Is 2:00-3:00 okay?  Or do you think we need more time?

**Comment by DanMorand** [comment] 2013-02-15 16:21
I don't know for sure how much time this will take for us. What I'm hoping to get is guidance on which steps are necessary, what specific syntax to use with Drush make if we've already got the Acquia stack installed, how to correct things if WxT installs but the db/site isn't showing in Acquia. I need to know where to plug in our own site names in the process, whether I need to manually create a db user in Acquia first (that came up as an error on a previous install attempt.)

**Comment by MaddyDaigle** [comment] 2013-02-15 16:27
I was only able to get it booked for an hour, but it's doubtful that someone else will want to use the line after the hour.

**Comment by Tikka** [comment] 2013-02-15 16:54
Here are some comments you might find useful on the experience we've been having.

The installation from the page https://github.com/wet-boew/wet-boew-drupal has worked through step 5. From previous experience we have taken a different path starting at step 6, which is very easy. Instructions for what we do are listed below in Step 6. 

The instructions on the page @MaddyDaigle  referenced, in Step 1, sub-step 4 of Build and Launch the WetKit Drupal Distribution fails (for us) with the error: Cannot move build into place. We did have some issues with checking out the last file, but that seems to have been resolved. Step 2 did not work for us, so we tried the following (our new step 6).

Step 6: Start the acquia drupal control panel and let it fire up. 
From the drop-down site list, select more
On the sites tab, click the import button
Click the browse button for site path, and navigate to your drupal_wet folder
Click the create new database option button
Enter a new db name
provide a sub-domain name
Click import and the new wetkit installation will run. Provide input as appropriate. We like the new interface for this, by the way.

We have not tried this on an existing database, because most of the time it gets so badly damaged by our (my) bashing around and experimentation that it's not generally a good idea.

**Comment by MaddyDaigle** [comment] 2013-02-15 17:42
@sylus Sent you an e-mail with the teleconference information.  Is it okay if one of my collegues attends as well?

**Comment by MaddyDaigle** [comment] 2013-02-15 17:44
Could anyone else who'd like to participate e-mail me at maddy.daigle@gmail.com? I'll send the teleconferencing info.

**Comment by sylus** [comment] 2013-02-15 17:48
Yeah no problem i'll help however I can. Though might be difficult without actually being there but will do my best.

**Comment by MaddyDaigle** [comment] 2013-02-15 17:49
If you'd prefer, I can set up Web Ex so we can screen share..

**Comment by sylus** [comment] 2013-02-15 17:53
Oh that would greatly speed things up!

**Comment by nrc-cnrc-web** [comment] 2013-02-21 19:33
Would someone who participated in that WebEx session be able to post the results of the discussion? I've tried getting it working with Acquia Dev Desktop/Git/Drush (on WIndows 7) and the drush make has never worked.

I'm rather new to this (Drupal/Drush) so it's quite possible I'm the problem, but if there is something that came out of this discussion I'd love to read about it just to be sure.

Cheers!

**Comment by Tikka** [comment] 2013-02-21 20:58
I did not participate in the discussion, but can help you with this @nrc-cnrc-web - I had trouble with all of this too. A lot of trouble. Now I've got a set of steps I follow that work, at least for me. I'll put it here in a few minutes.

**Comment by Tikka** [comment] 2013-02-21 21:10
1. Create the folder C:\Users\tikkababy\Sites\drupal_wet, where tikkababy is replaced by your user name. The folder acquial-drupal should already exist in C:\Users\tikkababy\Sites
2. Open git bash. In git bash change the folder to sites\drupal_wet

run the following 2 commands, as is, in git bash:
    git clone https://github.com/wet-boew/wet-boew-drupal.git drupal_wet/wet-boew-drupal;

```
drush make --prepare-install --no-gitinfofile --working-copy drupal_wet/wet-boew-drupal/build-wetkit.make  --yes
```
1. After it's all finished, open acquial-drupal control panel, and select more from the site list. Browse to the drupal_wet folder you created in step 1 for the site path.
   Choose to create a new database.
   Provide a new db name.
   Select an appropriate server, in my case localhost
   provide a subdomain name (never worked for me if I did not provide this).
   Leave the url path empty
   Click Import
2. Follow the instructions for the installation - selecting a language and all that.

Good luck.

**Comment by lampson** [comment] 2013-02-22 03:48
With any of your drush statements, you can use --verbose and --debug to get more information.  Then you could post the error message you're receiving.

**Comment by MaddyDaigle** [comment] 2013-02-22 19:20
The following are the instructions I wrote down based on the meeting:

_Drupal Make_

1) Ensure that Drush C:\Program Files\Drush\Php\php.ini memory_limit is around 256M
2) Go into git bash
3) `git clone https://github.com/wet-boew/wet-boew-drupal.git`
     - into a folder you've created on your local machine
4) `drush make --prepare-install --no-gitinfofile build-wetkit.make ../drupal-wet-main --yes`
    - cd into the folder you created

Note: Make sure you're an admin. :(

_Aquia Dev_

5) Create folder for your site.  In this case I will call it Sites
6) Create a sub folder for the drupal files. In this case I called it drupal_wet
7) Copy the files you got through the make process into this folder
5) Update your $PATH Environment Variable to add the following location:
C:\Program Files\acquia-drupal\mysql\bin;
9) Make sure php.ini filde under C:/Program Files/acquia-drupal/php5_3/bin has high enough memory_limit (200M or so should be good)
8) Go to C:\Windows\System32\drivers\etc\host
9) modify to this:

```
127.0.0.1       localhost
127.0.0.1       my-drupal  <-- Your new site
```

10) Open vhosts.conf under C:/Program Files/acquia-drupal/apache/conf/vhosts.conf
11) Add this to the end of the file

```
<VirtualHost *>
  ServerName rcmp-drupal
  DocumentRoot "C:\Documents and Settings\internet\Desktop\Sites\drupal_wet"      < ----- (The folder with your files!)
  <Directory "C:\Documents and Settings\internet\Desktop\Sites\drupal_wet">
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride All
    Order allow,deny
    Allow from all
  </Directory>
</VirtualHost>
```

12)You can make a short cut in your site folder to vhosts.conf and host so they're easier to get to!
13) Make sure you start your Drupal stack in Aquia dev desktop
13) Run the drush si command in your git bash.  In this case it would be:
`drush si wetkit wetkit_wetboew_selection_form.theme=wetkit_adaptivetheme --sites-subdir=drupal_wet --db-url=mysql://drupaluser@127.0.0.1:33066/wetkit_db --account-name=admin --account-pass=WetKit@2012 --account-mail=admin@example.com --site-mail=admin@example.com --site-name="Maddy is awesome!`
14) Go to Sites\drupal_wet\sites and make sure the third folder matches your server name (in this case my-drupal)
15) Access your site at: http://my-drupal:8082/

**Comment by nrc-cnrc-web** [comment] 2013-02-26 16:27
Thank you both for posting your instructions. I tried Tikka's method but ran into strange permission issues in the temp folders the make was using. I was installing on D: drive because my C: drive is a small SSD drive, but I don't see why that would cause permission issues (especially since my account is an administrator account).

I've given up for now, but will likely try again later this week/this weekend. Again, thank you both for your help!  :-)

**Comment by Tikka** [comment] 2013-02-26 18:23
I too have experienced some strange permission issues even while operating under admin privileges. From time to time, some files did not seem to get placed in the temp folder, and it failed at when files were moved from temp into the destination folder. When the process failed with this sort of error, there was sometimes difficulty with files hanging around, cluttering up the temp folder. The cluttering problem would eventually cause some permission errors that were resolved by manually clearing out the files generated by the second of the drush steps. If I managed to get by this, well, then the import through the acquia control panel would always work. 

In general, waiting a few days (or a week) to try downloading and installing the distribution again was often met with success, since changes seemed to be frequent. Persistence in attempting the steps has been the key to getting it to go, and the steps I outlined are the steps that were followed last Thursday afternoon, shortly before you posted @nrc-cnrc-web. If you need it, I could look at those steps again to see if anything was missed.

After achieving success, making backup copy of the final site folder has saved me from myself a number of times (it seems pretty easy to trash things, but I am relatively new to drupal and have been bashing around rather relentlessly).

All things considered, I've found it worth it to keep trying. We need the accessibility features and this last release has really improved a lot.

**Comment by nrc-cnrc-web** [comment] 2013-03-06 20:42
You're right @Tikka - it was worth it to keep trying. After a week away (and a few strange hoops to jump through), I was able to make it work. I don't understand why, but I had to work around using Drush on my Windows 7 machine.

I installed Ubuntu on it (dual boot), and did everything up to step 13 in the instructions provided by @MaddyDaigle through Linux. I then booted back into WIndows 7, started my Acquia stack, and used the "Import" option to install Wxt-Drupal. Worked like a charm on both my work PC and my laptop (both Windows 7, 64-bit machines).

Thank you again all for your suggestions!  :-)

**Comment by mrjmoskau** [comment] 2013-03-19 14:36
@nrc-cnrc-web Can you just clarify the Ubuntu / Windows 7 switch-over? Did you build the site to a database server so that both OSes could talk to the same DB? Did you build the site to a "shared" drive that was accessible from Ubuntu and Windows 7?

@Tikka In terms of backing up the site folder, do you think it would have been possible to take that backup and move it from one machine to another, or was that just in case you tried a change / upgrade that would break something that was working before?

Thanks to everyone for their comments and suggestions. I'll be getting my feet wet "any day now" to try to build this up for our group...

**Comment by Tikka** [comment] 2013-03-19 15:45
@mrjmoskau For my purposes it was simply in the event I broke something, which I managed to do regularly. All experimentation has taken place on my local machine, and a more experienced colleague is using the migrating features in wetkit to move the work that actually functions properly off of my machine and onto our staging server.

**Comment by sylus** [comment] 2013-04-16 05:09
Closing this issue as I think everything is solved? Please reopen if any problems or questions arise.

**Closed as completed by sylus** 2013-04-16 05:09 UTC
Labels: Support Request
