### ISSUE TITLE
Unable to checkout revision 467bddf 

### ISSUE THREAD

**Issue by terrerouge** [wet-boew/wet-boew-drupal#596] opened 2012-12-05 16:16 UTC
Trying to do a fresh install of the setup, failing on this revision (right after wet-boew is cloned).

**Comment by sylus** [comment] 2012-12-05 16:19
Works for me and on Travis. Possibly a hiccup with github?

**Comment by lpgascon** [comment] 2012-12-05 16:31
I'm also having issues (errors) using the latest Git + Drush versions. But maybe it's the GitHub... I'm running a few installs with different versions. We'll see

**Comment by terrerouge** [comment] 2012-12-05 16:38
Thanks @lpgascon  - if there's a workaround please let me know.

**Comment by sylus** [comment] 2012-12-05 16:45
Our CI server continuously checks our build out and reports any errors. The latest revision works and am having no errors. I need more information to help. Can either of you paste your errors here as must be something I am missing. Will watch this issue closely today.

**Comment by terrerouge** [comment] 2012-12-05 16:53
I ran verbose on the drush make, but all I'm seeing is:

Executing: git clone https://github.com/wet-boew/wet-boew.git /tmp/drush_tmp_1354726197_50bf7b35a00b9/wet-boew --verbose --progress
wet-boew cloned from https://github.com/wet-boew/wet-boew.git.                                       [ok]
Executing: git checkout 467bddf
Unable to checkout revision 467bddf                                                                  [error]

**Comment by uottawa-wcms** [comment] 2012-12-05 16:56
Also having this issue just now. To reproduce, I:
1. Created a new directory 
2. Cloned in the latest version of the profile to profiles/wetkit (worked fine)
3. Ran the drush make.
4. Drush make executed fine up until the very last step "wet-boew cloned from https://github.com/wet-boew/wet-boew.git", so the clone is fine from wetkit.
5. But then I get "Unable to checkout revision 467bddf" [error] immediately after.
6. There are no files in my base directory afterwards either (since the make had an error)

It looks like drush make is unable to check out the specific ref you've specified of wet-boew (ref 467bddf). Reviewing the "gh-pages" branch of wet-boew, I am unable to locate a revision with that ref.

I also noticed today that the wet-boew library has changed (though this might be a different problem):

When I was working on it last week (specific date of my clone: Nov 29), the libraries/wet-boew/build directory had folders /js and /theme-\* and lots of other things.

Now, when I clone the wet-boew library (without that specific reference, so that I'm getting latest version of gh-pages branch), I get only a /lib directory and the varions .rb, .xml, .sh and .properties files. I get none of the compiled components (grids, js, or any of the theme directories).

If the second part is a different issue, I'll be happy to file it separately, but it looks like the wet-boew library might be a bit messed up.

Update: Now tested on Mac and Windows environment, broken on both. Unable to test on Unix, sorry.

**Comment by uottawa-wcms** [comment] 2012-12-05 17:05
On further review, it looks like the files have been moved from /build to /dist. Not sure why, but it's breaking the includes in the Drupal variant.

**Comment by sylus** [comment] 2012-12-05 17:22
My newest code fixes that and points to /dist. This is because of changes from wet-boew.

**Comment by lpgascon** [comment] 2012-12-05 17:23
Using Bash version 5.7 gives me a bunch of errors so i reverted to 5.4

I still get the warning for "Could not locate file_entity version 7.x-7.x-2.0-unstable7"
and the "Unable to checkout revision 467bddf" as well

Has anyone tried running the "make" command using Drush 5.7 (under Windows Server)? 
Just wandering why i get so many errors compared to 5.4 (or if anyone is having the same issue)

**Comment by sylus** [comment] 2012-12-05 17:25
Drush 5.7 has errors with windows this is why we state in our documentation to only use 5.4. Drush 5.8 will resolve these errors and will be released shortly.

**Comment by sylus** [comment] 2012-12-05 17:25
As for missing revision for #467bddf something had to have changed with wet-boew repo. Looking into it.

**Comment by sylus** [comment] 2012-12-05 17:29
K I fixed the revision issue but not sure what happened with the other one as it was working. Will be talking with WET-BOEW shortly on this.

**Comment by sylus** [comment] 2012-12-05 17:32
K so looks like all of the issues are now resolved :) https://travis-ci.org/wet-boew/wet-boew-drupal/builds/3516099

As mentioned for drush, I have asked for the windows installer maintainers to release drush 5.8 thinking should be released within a day.

**Comment by sylus** [comment] 2012-12-05 17:42
Closing issue as resolved :) Please reopen if problems persist! Thanks guys!

**Comment by sylus** [comment] 2012-12-05 23:01
More of a problem then thought: https://github.com/wet-boew/wet-boew/issues/817

**Comment by LaurentGoderre** [comment] 2012-12-05 23:23
Much more of an issue than I expected too

**Comment by sylus** [comment] 2012-12-06 03:34
Thanks to the awesome @LaurentGoderre this is now fixed! 

Also thanks everyone in this queue for bringing this to our attention. We temporarily are using a fork of wet-boew but will merge back with wet-boew gh-pages branch in a day or so!

**Closed as completed by sylus** 2012-12-06 03:34 UTC
