### ISSUE TITLE
Tab Interface

### ISSUE THREAD

**Issue by elaberge74** [wet-boew/wet-boew-drupal#909] opened 2013-05-07 20:02 UTC
Hi, I need some help.

I created a Content Type with a custom field as a "Tabbed Interface".

I created my content with this Content type.  By default, my 2 images appear one under the other.

I created a Custom page with a Wetkit layout (Penfield).
I added content to the "content1" pane.  I choose "Page Content" from the left menu, and add my field "ImagesTop3" ( the name that I gave to my field of my Custom Content type)

My Images appear.. but nothing like a tab ( tabs-style-2 design ) from  : http://wet-boew.github.io/wet-boew/demos/tabs/tabs-eng.html

Is there a way to do that ?
I'm really sorry if it's not clear... I'm lost with it..

**Comment by StephenOTT** [comment] 2013-05-08 14:38
@elaberge74 tabbed interface was designed to be used with Fieldable Panel Panes (FPP) (Structure>Fieldable Panel Panes).

Have you been able to get it working with FPP?

**Comment by elaberge74** [comment] 2013-05-08 15:12
I'm sorry, what is FPP ?

**Comment by StephenOTT** [comment] 2013-05-08 15:19
>  Fieldable Panel Panes (FPP)

**Comment by StephenOTT** [comment] 2013-05-08 15:19
> @elaberge74 tabbed interface was designed to be used with Fieldable Panel Panes (FPP) (Structure>Fieldable Panel Panes).

**Comment by sylus** [comment] 2013-05-08 15:30
Hey @elaberge74 + @StephenOTT there is an addition coming through the pipe this week when I finally release RC2 that will instead be leveraging a views plugin for tabbed interface. Much more in line with Drupal best practices.

I have a blog I am putting up tomorrow that will be discussing these changes, will post back here tomorrow.

**Comment by elaberge74** [comment] 2013-05-08 15:33
Super ! Do you think it's going to be easy to update to RC2 ?   I have a lot of work completed with RC1

Thanks  Eric

**Comment by sylus** [comment] 2013-05-08 15:44
I have committed to an upgrade path. The plan for RC2 is that I am going to try and catch most of the problems I think will arise with hook_update_n however might not catch them all. There is where I am hoping to get feedback from you and other people on issues that are arising when attempting to use RC2.

I will then do another release to address those issues (ideally the same week). Essentially this means you won't want to upgrade your main site till all of the issues with the update to RC2 is addressed on your testing site.

I like this plan because it means new users can get all of the major benefits of RC2 (better ie support, mini panels, deployment, ckeditor, and code quality fixes) and I can then just focus on upgrade path issues for existing users which might be very minimal or involve some extra steps.

Based on the experience learned from this process future upgrades might not require an additional release. However have to start somewhere :)

**Comment by sylus** [comment] 2013-09-05 14:26
Tabbed interface has been removed till have a more feature robust integration with beans.

**Closed as completed by sylus** 2013-09-05 14:26 UTC
